# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baeminchan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baeminchan
  pod 'Alamofire', '~> 4.7'
  pod 'XLPagerTabStrip', '~> 8.0'


end
